const colors = {
  light: {
    text: '#0a0a0a',
    tint: '#ff3b30',
    background: '#0d0d0d',
    foreground: '#f5f5f5',
    card: '#1c1c1e',
    cardForeground: '#f5f5f5',
    primary: '#ff3b30',
    primaryForeground: '#ffffff',
    secondary: '#1c1c1e',
    secondaryForeground: '#e5e5e5',
    muted: '#1c1c1e',
    mutedForeground: '#636366',
    accent: '#ff3b30',
    accentForeground: '#ffffff',
    destructive: '#ff453a',
    destructiveForeground: '#ffffff',
    border: '#2c2c2e',
    input: '#2c2c2e',
  },
  dark: {
    text: '#0a0a0a',
    tint: '#ff3b30',
    background: '#0d0d0d',
    foreground: '#f5f5f5',
    card: '#1c1c1e',
    cardForeground: '#f5f5f5',
    primary: '#ff3b30',
    primaryForeground: '#ffffff',
    secondary: '#1c1c1e',
    secondaryForeground: '#e5e5e5',
    muted: '#1c1c1e',
    mutedForeground: '#636366',
    accent: '#ff3b30',
    accentForeground: '#ffffff',
    destructive: '#ff453a',
    destructiveForeground: '#ffffff',
    border: '#2c2c2e',
    input: '#2c2c2e',
  },
  radius: 12,
};

export default colors;
