const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");

// Google Sign-In drags in a mix of Swift and Objective-C pods. Swift can only
// `import` an Objective-C pod that ships a module map, and CocoaPods emits one
// for a static library only when the pod is declared with modular headers:
//
//   AppCheckCore (Swift)  -> GoogleUtilities, RecaptchaInterop
//   GTMAppAuth   (Swift)  -> AppAuth, GTMSessionFetcher
//
// Without the first pair `pod install` fails outright; without the second the
// build gets as far as compiling GTMAppAuth and then reports
// "no such module 'AppAuth'".
//
// This lives in a plugin rather than in ios/Podfile because ios/ is gitignored
// and regenerated by `expo prebuild --clean`, which silently discards any hand
// edit made there.
const MARKER = "  # withModularHeaders: Swift pods need module maps";
const POD_LINES = [
  MARKER,
  "  pod 'GoogleUtilities', :modular_headers => true",
  "  pod 'RecaptchaInterop', :modular_headers => true",
  "  pod 'AppAuth', :modular_headers => true",
  "  pod 'GTMSessionFetcher', :modular_headers => true",
];

const ANCHOR = "  use_expo_modules!\n";

module.exports = function withModularHeaders(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      const contents = fs.readFileSync(podfile, "utf8");

      // Keyed on the marker, not on a pod name: an older prebuild left the
      // first two lines behind, and matching those would skip the rest
      // forever.
      if (contents.includes(MARKER)) return cfg;
      if (!contents.includes(ANCHOR)) {
        throw new Error(
          "withModularHeaders: could not find `use_expo_modules!` in the " +
            "Podfile. The Expo template changed; update this plugin.",
        );
      }
      if (contents.includes("RecaptchaInterop")) {
        throw new Error(
          "withModularHeaders: the Podfile already declares modular headers " +
            "without this plugin's marker, so appending would duplicate pod " +
            "declarations. Run `expo prebuild --clean --platform ios`.",
        );
      }

      fs.writeFileSync(
        podfile,
        contents.replace(ANCHOR, ANCHOR + POD_LINES.join("\n") + "\n"),
      );
      return cfg;
    },
  ]);
};
