const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");

// Google Sign-In pulls in AppCheckCore, a Swift pod that cannot be built as a
// static library against GoogleUtilities/RecaptchaInterop unless those two
// generate module maps. Without this, `pod install` fails outright.
//
// This lives in a plugin rather than in ios/Podfile because ios/ is gitignored
// and regenerated by `expo prebuild --clean`, which silently discards any hand
// edit made there.
const POD_LINES = [
  "  pod 'GoogleUtilities', :modular_headers => true",
  "  pod 'RecaptchaInterop', :modular_headers => true",
];

const ANCHOR = "  use_expo_modules!\n";

module.exports = function withModularHeaders(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      const contents = fs.readFileSync(podfile, "utf8");

      if (contents.includes("RecaptchaInterop")) return cfg;
      if (!contents.includes(ANCHOR)) {
        throw new Error(
          "withModularHeaders: could not find `use_expo_modules!` in the " +
            "Podfile. The Expo template changed; update this plugin.",
        );
      }

      fs.writeFileSync(
        podfile,
        contents.replace(ANCHOR, ANCHOR + POD_LINES.join("\n") + "\n"),
      );
      return cfg;
    },
  ]);
};
